function createEnum(keys) {
    const obj = {};
    for (const [index, key] of keys.entries()) {
      if (key === null) continue;
      obj[key] = index;
      obj[index] = key;
    }
    return obj;
  }

const EventsA = module.exports.EventsA = [
    "apiRequest",
    "apiResponse",
    "applicationCommandCreate",
    "applicationCommandDelete",
    "applicationCommandUpdate",
    "channelCreate",
    "channelDelete",
    "channelPinsUpdate",
    "channelUpdate",
    "debug",
    "emojiCreate",
    "emojiDelete",
    "emojiUpdate",
    "error",
    "guildBanAdd",
    "guildBanRemove",
    "guildCreate",
    "guildDelete",
    "guildIntegrationsUpdate",
    "guildMemberAdd",
    "guildMemberAvailable",
    "guildMemberRemove",
    "guildMembersChunk",
    "guildMemberUpdate",
    "guildUnavailable",
    "guildUpdate",
    "interaction",
    "interactionCreate",
    "invalidated",
    "invalidRequestWarning",
    "inviteCreate",
    "inviteDelete",
    "message",
    "messageCreate",
    "messageDelete",
    "messageDeleteBulk",
    "messageReactionAdd",
    "messageReactionRemove",
    "messageReactionRemoveAll",
    "messageReactionRemoveEmoji",
    "messageUpdate",
    "presenceUpdate",
    "rateLimit",
    "ready",
    "roleCreate",
    "roleDelete",
    "roleUpdate",
    "shardDisconnect",
    "shardError",
    "shardReady",
    "shardReconnecting",
    "shardResume",
    "stageInstanceCreate",
    "stageInstanceDelete",
    "stageInstanceUpdate",
    "stickerCreate",
    "stickerDelete",
    "stickerUpdate",
    "threadCreate",
    "threadDelete",
    "threadListSync",
    "threadMembersUpdate",
    "threadMemberUpdate",
    "threadUpdate",
    "typingStart",
    "userUpdate",
    "voiceStateUpdate",
    "warn",
    "webhookUpdate"
]

module.exports.Events = {
    "apiRequest": "apiRequest",
        "apiResponse": "apiResponse",
        "applicationCommandCreate": "applicationCommandCreate",
        "applicationCommandDelete": "applicationCommandDelete",
        "applicationCommandUpdate": "applicationCommandUpdate",
        "channelCreate": "channelCreate",
        "channelDelete": "channelDelete",
        "channelPinsUpdate": "channelPinsUpdate",
        "channelUpdate": "channelUpdate",
        "debug": "debug",
        "emojiCreate": "emojiCreate",
        "emojiDelete": "emojiDelete",
        "emojiUpdate": "emojiUpdate",
        "error": "error",
        "guildBanAdd": "guildBanAdd",
        "guildBanRemove": "guildBanRemove",
        "guildCreate": "guildCreate",
        "guildDelete": "guildDelete",
        "guildIntegrationsUpdate": "guildIntegrationsUpdate",
        "guildMemberAdd": "guildMemberAdd",
        "guildMemberAvailable": "guildMemberAvailable",
        "guildMemberRemove": "guildMemberRemove",
        "guildMembersChunk": "guildMembersChunk",
        "guildMemberUpdate": "guildMemberUpdate",
        "guildUnavailable": "guildUnavailable",
        "guildUpdate": "guildUpdate",
        "interaction": "interaction",
        "interactionCreate": "interactionCreate",
        "invalidated": "invalidated",
        "invalidRequestWarning": "invalidRequestWarning",
        "inviteCreate": "inviteCreate",
        "inviteDelete": "inviteDelete",
        "message": "message",
        "messageCreate": "messageCreate",
        "messageDelete": "messageDelete",
        "messageDeleteBulk": "messageDeleteBulk",
        "messageReactionAdd": "messageReactionAdd",
        "messageReactionRemove": "messageReactionRemove",
        "messageReactionRemoveAll": "messageReactionRemoveAll",
        "messageReactionRemoveEmoji": "messageReactionRemoveEmoji",
        "messageUpdate": "messageUpdate",
        "presenceUpdate": "presenceUpdate",
        "rateLimit": "rateLimit",
        "ready": "ready",
        "roleCreate": "roleCreate",
        "roleDelete": "roleDelete",
        "roleUpdate": "roleUpdate",
        "shardDisconnect": "shardDisconnect",
        "shardError": "shardError",
        "shardReady": "shardReady",
        "shardReconnecting": "shardReconnecting",
        "shardResume": "shardResume",
        "stageInstanceCreate": "stageInstanceCreate",
        "stageInstanceDelete": "stageInstanceDelete",
        "stageInstanceUpdate": "stageInstanceUpdate",
        "stickerCreate": "stickerCreate",
        "stickerDelete": "stickerDelete",
        "stickerUpdate": "stickerUpdate",
        "threadCreate": "threadCreate",
        "threadDelete": "threadDelete",
        "threadListSync": "threadListSync",
        "threadMembersUpdate": "threadMembersUpdate",
        "threadMemberUpdate": "threadMemberUpdate",
        "threadUpdate": "threadUpdate",
        "typingStart": "typingStart",
        "userUpdate": "userUpdate",
        "voiceStateUpdate": "voiceStateUpdate",
        "warn": "warn",
        "webhookUpdate": "webhookUpdate",
}

module.exports.ClientHeaders = {
    "COMMANDS": `CLIENT_COMMANDS`,
    "READY": `CLIENT_READY`
}