const Client = require("./classes/client");
const DJSBuilders = require("@discordjs/builders");
const { pages, ContextMenuBuilder } = require("discord.js-util");

module.exports.Client = Client;
module.exports.commandBuilder = DJSBuilders.SlashCommandBuilder;
module.exports.Pages = pages;
module.exports.contextBuilder = ContextMenuBuilder;
module.exports.DocsJSON = require("../docs.json");
module.exports.Colors = {
    'DEFAULT': 'DEFAULT',
    'WHITE': 'WHITE',
    'AQUA': 'AQUA',
    'GREEN': 'GREEN',
    'BLUE': 'BLUE',
    'YELLOW': 'YELLOW',
    'PURPLE': 'PURPLE',
    'LUMINOUS_VIVID_PINK': 'LUMINOUS_VIVID_PINK',
    'FUCHSIA': 'FUCHSIA',
    'GOLD': 'GOLD',
    'ORANGE': 'ORANGE',
    'RED': 'RED',
    'GREY': 'GREY',
    'DARKER_GREY': 'DARKER_GREY',
    'NAVY': 'NAVY',
    'BLURPLE': 'BLURPLE',
}
module.exports.Events = {
    "apiRequest": "apiRequest",
    "apiResponse": "apiResponse",
    "applicationCommandCreate": "applicationCommandCreate",
    "applicationCommandDelete": "applicationCommandDelete",
    "applicationCommandUpdate": "applicationCommandUpdate",
    "channelCreate": "channelCreate",
    "channelDelete": "channelDelete",
    "channelPinsUpdate": "channelPinsUpdate",
    "channelUpdate": "channelUpdate",
    "debug": "debug",
    "emojiCreate": "emojiCreate",
    "emojiDelete": "emojiDelete",
    "emojiUpdate": "emojiUpdate",
    "error": "error",
    "guildBanAdd": "guildBanAdd",
    "guildBanRemove": "guildBanRemove",
    "guildCreate": "guildCreate",
    "guildDelete": "guildDelete",
    "guildIntegrationsUpdate": "guildIntegrationsUpdate",
    "guildMemberAdd": "guildMemberAdd",
    "guildMemberAvailable": "guildMemberAvailable",
    "guildMemberRemove": "guildMemberRemove",
    "guildMembersChunk": "guildMembersChunk",
    "guildMemberUpdate": "guildMemberUpdate",
    "guildUnavailable": "guildUnavailable",
    "guildUpdate": "guildUpdate",
    "interaction": "interaction",
    "interactionCreate": "interactionCreate",
    "invalidated": "invalidated",
    "invalidRequestWarning": "invalidRequestWarning",
    "inviteCreate": "inviteCreate",
    "inviteDelete": "inviteDelete",
    "message": "message",
    "messageCreate": "messageCreate",
    "messageDelete": "messageDelete",
    "messageDeleteBulk": "messageDeleteBulk",
    "messageReactionAdd": "messageReactionAdd",
    "messageReactionRemove": "messageReactionRemove",
    "messageReactionRemoveAll": "messageReactionRemoveAll",
    "messageReactionRemoveEmoji": "messageReactionRemoveEmoji",
    "messageUpdate": "messageUpdate",
    "presenceUpdate": "presenceUpdate",
    "rateLimit": "rateLimit",
    "ready": "ready",
    "roleCreate": "roleCreate",
    "roleDelete": "roleDelete",
    "roleUpdate": "roleUpdate",
    "shardDisconnect": "shardDisconnect",
    "shardError": "shardError",
    "shardReady": "shardReady",
    "shardReconnecting": "shardReconnecting",
    "shardResume": "shardResume",
    "stageInstanceCreate": "stageInstanceCreate",
    "stageInstanceDelete": "stageInstanceDelete",
    "stageInstanceUpdate": "stageInstanceUpdate",
    "stickerCreate": "stickerCreate",
    "stickerDelete": "stickerDelete",
    "stickerUpdate": "stickerUpdate",
    "threadCreate": "threadCreate",
    "threadDelete": "threadDelete",
    "threadListSync": "threadListSync",
    "threadMembersUpdate": "threadMembersUpdate",
    "threadMemberUpdate": "threadMemberUpdate",
    "threadUpdate": "threadUpdate",
    "typingStart": "typingStart",
    "userUpdate": "userUpdate",
    "voiceStateUpdate": "voiceStateUpdate",
    "warn": "warn",
    "webhookUpdate": "webhookUpdate",
}